name = "curriculo-interativo"
main = "./server.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Variáveis de ambiente
[vars]
ENVIRONMENT = "production"

# Build configuration
[build]
command = "npm run build"