name = "curriculo-interativo"
main = "./server.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Variáveis de ambiente
[vars]
ENVIRONMENT = "production"

# Assets configuration - usando [assets] em vez de [site] para melhor compatibilidade
[assets]
directory = "./build/client"

# Build command
[build]
command = "npm run build"